-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 13:49:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema rotasviagens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rotasviagens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rotasviagens` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carga` (
  `id_carga` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `quantidadeuni` INT NOT NULL,
  `peso_total` INT NOT NULL,
  `valor_total` FLOAT NOT NULL,
  `data_fabricacao` DATE NOT NULL,
  `data_validade` DATE NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_carga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rotasviagens`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rotasviagens`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(100) NOT NULL,
  `num_casa` INT(11) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `uf` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`motorista` (
  `id_motorista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cnh` VARCHAR(45) NOT NULL,
  `categoria_cnh` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id_motorista`),
  INDEX `fk_motorista_endereco_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_motorista_endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `rotasviagens`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `rotasviagens` ;

-- -----------------------------------------------------
-- Table `rotasviagens`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rotasviagens`.`funcionario` (
  `id_funcionario` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `identidade` INT(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_endereco_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `rotasviagens`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
